

create table country(
                        id bigint generated by default as identity
                            primary key,
                        name varchar(255),
                        continent varchar(255)
);
create table host
(
    id bigint generated by default as identity
        primary key,
    name varchar(255),
    surname varchar(255),
    country_id bigint references country
);
CREATE TABLE accommodation (
                               id SERIAL PRIMARY KEY,
                               name VARCHAR(255) NOT NULL,
                               category VARCHAR(50) NOT NULL,
                               is_reserved BOOLEAN DEFAULT FALSE,
                               num_rooms INTEGER,
                               host_id BIGINT,
                               CONSTRAINT fk_host FOREIGN KEY (host_id) REFERENCES host(id)
);




create table app_users(

                         username                   varchar(255)
                             primary key,
                         password                   varchar(255),
                         name                       varchar(255),
                         surname                    varchar(255),
                         is_account_non_expired     boolean default true,
                         is_account_non_locked      boolean default true,
                         is_credentials_non_expired boolean default true,
                         is_enabled                 boolean default true,
                         role                       varchar(50)
);

create table guest (
                       id bigint generated by default as identity primary key,
                       name varchar(255),
                       surname varchar(255),
                       country_id bigint references country
);

-- Релација меѓу guest и host
create table guest_host_list (
                                 guest_list_id bigint references guest(id),
                                 host_list_id bigint references host(id),
                                 primary key (guest_list_id, host_list_id)
);

-- Релација меѓу guest и accommodation (wishlist)
create table guest_wish_list (
                                 guest_id bigint references guest(id),
                                 wish_list_id bigint references accommodation(id),
                                 primary key (guest_id, wish_list_id)
);
